#!/bin/zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# unix aliases
export PATH="/home/lokun/scripts:/home/lokun/.local/bin:/usr/local/matlab/bin:$PATH"
alias s='sudo'
# alias sl='sudo $(!!)' TODO figure out if possible
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lr='ls -R'
alias c='cd'
alias c.='cd ..'
alias md='mkdir'
alias rd='rmdir'

# program aliases
alias p='sudo pacman'
alias ps='sudo pacman -S'
alias psy='sudo pacman -Sy'
alias psyu='sudo pacman -Syu'
alias pr='sudo pacman -R'
alias sy='sudo systemctl'
alias sye='sudo systemctl enable'
alias syon='sudo systemctl start'
alias syof='sudo systemctl stop'

alias btctl='bluetoothctl'
alias e='emacs'
alias v='nvim'
alias vp='nvimpager -p'
alias g='git'

alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zinit ice depth=1; zinit light romkatv/powerlevel10k

[[ -s /home/lokun/.autojump/etc/profile.d/autojump.sh ]] && source /home/lokun/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u

# opam configuration
[[ ! -r /home/lokun/.opam/opam-init/init.zsh ]] || source /home/lokun/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
